export enum ColorCodes {
    black = "§0",
    darkblue = "§1",
    darkgreen = "§2",
    darkaqua = "§3",
    darkred = "§4",
    darkpurple = "§5",
    gold = "§6",
    grey = "§7",
    darkgrey = "§8",
    blue = "§9",
    green = "§a",
    aqua = "§b",
    red = "§c",
    lightpurple = "§d",
    yellow = "§e",
    white = "§f",
    obfuscated = "§k",
    bold = "§l",
    strikethrough = "§m",
    underline = "§n",
    italic = "§o",
    reset = "§r"
}