export const Locale_EN_US:Map<string,string> = new Map<string,string>([
    ["player_welcome", "Welcome %s. This server has MCWL installed. For a list of all commands, type ,help in chat."],
    ["cmd_not_found", "Command not found. Use ,help for a list of all commands."],
    ["cmd_return_default", "Command format does not exist, use ,help %s for a list of all command formats."],
    ["cmd_name_ascend", "ascend"],
    ["cmd_name_blocksint", "blocksint"],
    ["cmd_name_blocksmodified", "blocksmodified"],
    ["cmd_name_crouchtime", "crouchtime"],
    ["cmd_name_descend", "descend"],
    ["cmd_name_distancemoved", "distancemoved"],
    ["cmd_name_firstjoined", "firstjoined"],
    ["cmd_name_floor", "floor"],
    ["cmd_name_goto", "goto"],
    ["cmd_name_help", "help"],
    ["cmd_name_playerjoined", "playerjoined"],
    ["cmd_name_playtime", "playtime"],
    ["cmd_name_setblock", "setblock"],
    ["cmd_name_spawn", "spawn"],
    ["cmd_name_sudo", "sudo"],
    ["cmd_name_top", "top"],
    ["cmd_description_ascend", "Teleports player to upper level."],
    ["cmd_description_blocksint", "Displays number of interactions with blocks."],
    ["cmd_description_blocksmodified", "Displays number of blocks modified by player."],
    ["cmd_description_crouchtime", "Displays total time player has sneaked in ticks."],
    ["cmd_description_descend", "Teleports player to lower level."],
    ["cmd_description_distancemoved", "Displays total distance travelled by player."],
    ["cmd_description_firstjoined", "Displays date of player's first login to the server."],
    ["cmd_description_floor", "Teleports player to the highest solid block below them."],
    ["cmd_description_goto", "Teleports player to the nearest block on crosshair."],
    ["cmd_description_help", "Pov you forgot your own command syntax smh."],
    ["cmd_description_playerjoined", "Displays number of times player has joined world."],
    ["cmd_description_playtime", "Displays playtime of player."],
    ["cmd_description_setblock", "Fills a block location with specified block."],
    ["cmd_description_spawn", "Spawns entities."],
    ["cmd_description_sudo", "Changes name shown in chat."],
    ["cmd_description_top", "Teleports player to the highest solid block above them."],
    ["cmd_return_ascend_0_failure", "Unable to find teleport location."],
    ["cmd_return_ascend_0_success", "Ascended %d levels."],
    ["cmd_return_ascend_1_failure", "Unable to find teleport location."],
    ["cmd_return_ascend_1_success", "Ascended %d levels."],
    ["cmd_return_ascend_2_failure", "Unable to find teleport location."],
    ["cmd_return_ascend_2_success", "Ascended 1 level."],
    ["cmd_return_blocksint_0_info", "Username: %s, [%s] : %d"],
    ["cmd_return_blocksmodified_0_broken_info", "%s has broken %d %s."],
    ["cmd_return_blocksmodified_0_placed_info", "%s has placed %d %s."],
    ["cmd_return_blocksmodified_0_failure", "Block Name %s is invalid."],
    ["cmd_return_crouchtime_0_info", "%s has crouched a total of %d game ticks."],
    ["cmd_return_descend_0_failure", "Unable to find teleport location."],
    ["cmd_return_descend_0_success", "Descended %d levels."],
    ["cmd_return_descend_1_failure", "Unable to find teleport location."],
    ["cmd_return_descend_1_success", "Descended %d levels."],
    ["cmd_return_descend_2_failure", "Unable to find teleport location."],
    ["cmd_return_descend_2_success", "Descended 1 level."],
    ["cmd_return_distancemoved_0_info", "%s has travelled a total of %d blocks ingame."],
    ["cmd_return_firstjoined_0_info","%s first joined this world on %s"],
    ["cmd_return_floor_0_failure", "Unable to find teleport location."],
    ["cmd_return_floor_0_success", "Teleported %s to floor."],
    ["cmd_return_goto_0_success", "%s teleported from [%d, %d, %d] to [%d, %d, %d]."],
    ["cmd_return_goto_0_failure", "Solid Blocks on cursor not found."],
    ["cmd_return_help_0_success", "%s - %s.\nFormat:%s"],
    ["cmd_return_help_0_failure", "Command %s not found, use ,help for a list of all commands."],
    ["cmd_return_help_1_success", "List of all avaliable commands:\n%s"],
    ["cmd_return_playerjoined_0_info", "%s has joined this world %d times."],
    ["cmd_return_playtime_0_info", "%s has played for %d ticks."],
    ["cmd_return_setblock_0_success", "%s placed at [%d, %d, %d]."],
    ["cmd_return_spawn_0_success", "Spawned %d %s at [%d, %d, %d]."],
    ["cmd_return_sudo_0_success", "%s has been nicked as %s for %s."],
    ["cmd_return_sudo_1_off_success", "Sudo module has been toggled off."],
    ["cmd_return_sudo_1_on_success", "Sudo module has been toggled on."],
    ["cmd_return_sudo_1_failure", "Unexpected '%s' at <on|off|toggle:string>."],
    ["cmd_return_top_0_failure", "Unable to find teleport location."],
    ["cmd_return_top_0_success", "Teleported %s to ceiling."],
    ["cmd_args_levels", "levels"],
    ["cmd_args_padding", "padding"],
    ["cmd_args_target", "target"],
    ["cmd_args_statType", "statType"],
    ["cmd_args_blockName", "blockName"],
    ["cmd_args_blocksBroken", "blocksBroken"],
    ["cmd_args_blocksPlaced", "blocksPlaced"],
    ["cmd_args_command", "command"],
    ["cmd_args_position", "position"],
    ["cmd_args_block", "block"],
    ["cmd_args_entity", "entity"],
    ["cmd_args_count", "count"],
    ["cmd_args_name", "name"],
    ["cmd_args_sudoOptions", "on|off|toggle"],
    ["cmd_args_sudo_on", "on"],
    ["cmd_args_sudo_off", "off"],
    ["cmd_args_sudo_toggle", "toggle"],

])
export class Locale {
    language:string
    languageMap:Map<string,string>
    constructor(language:string, languageMap:Map<string,string>) {
        this.language = language
        this.languageMap = languageMap;
    }
    get(s:string):string {
        return this.languageMap.get(s);
    }
}
export const locale:Locale = new Locale("en_us",Locale_EN_US);