export let molangQueries: Map<string, boolean> = new Map<string, boolean>([
    ["mcwl:molangquery:blocking",undefined],
    ["mcwl:molangquery:can_climb",undefined],
    ["mcwl:molangquery:can_damage_nearby_mobs",undefined],
    ["mcwl:molangquery:can_fly",undefined],
    ["mcwl:molangquery:can_power_jump",undefined],
    ["mcwl:molangquery:can_swim",undefined],
    ["mcwl:molangquery:can_walk",undefined],
    ["mcwl:molangquery:facing_target_to_range_attack",undefined],
    ["mcwl:molangquery:has_cape",undefined],
    ["mcwl:molangquery:has_collision",undefined],
    ["mcwl:molangquery:has_gravity",undefined],
    ["mcwl:molangquery:has_rider",undefined],
    ["mcwl:molangquery:has_target",undefined],
    ["mcwl:molangquery:is_admiring",undefined],
    ["mcwl:molangquery:is_alive",undefined],
    ["mcwl:molangquery:is_angry",undefined],
    ["mcwl:molangquery:is_attached_to_entity",undefined],
    ["mcwl:molangquery:is_avoiding_block",undefined],
    ["mcwl:molangquery:is_avoiding_mobs",undefined],
    ["mcwl:molangquery:is_baby",undefined],
    ["mcwl:molangquery:is_breathing",undefined],
    ["mcwl:molangquery:is_bribed",undefined],
    ["mcwl:molangquery:is_carrying_block",undefined],
    ["mcwl:molangquery:is_casting",undefined],
    ["mcwl:molangquery:is_celebrating",undefined],
    ["mcwl:molangquery:is_celebrating_special",undefined],
    ["mcwl:molangquery:is_charged",undefined],
    ["mcwl:molangquery:is_charging",undefined],
    ["mcwl:molangquery:is_chested",undefined],
    ["mcwl:molangquery:is_critical",undefined],
    ["mcwl:molangquery:is_croaking",undefined],
    ["mcwl:molangquery:is_dancing",undefined],
    ["mcwl:molangquery:is_delayed_attacking",undefined],
    ["mcwl:molangquery:is_eating",undefined],
    ["mcwl:molangquery:is_eating_mob",undefined],
    ["mcwl:molangquery:is_elder",undefined],
    ["mcwl:molangquery:is_emoting",undefined],
    ["mcwl:molangquery:is_enchanted",undefined],
    ["mcwl:molangquery:is_fire_immune",undefined],
    ["mcwl:molangquery:is_first_person",undefined],
    ["mcwl:molangquery:is_ghost",undefined],
    ["mcwl:molangquery:is_gliding",undefined],
    ["mcwl:molangquery:is_grazing",undefined],
    ["mcwl:molangquery:is_idling",undefined],
    ["mcwl:molangquery:is_ignited",undefined],
    ["mcwl:molangquery:is_illager_captain",undefined],
    ["mcwl:molangquery:is_in_contact_with_water",undefined],
    ["mcwl:molangquery:is_in_love",undefined],
    ["mcwl:molangquery:is_in_ui",undefined],
    ["mcwl:molangquery:is_in_water",undefined],
    ["mcwl:molangquery:is_in_water_or_rain",undefined],
    ["mcwl:molangquery:is_interested",undefined],
    ["mcwl:molangquery:is_invisible",undefined],
    ["mcwl:molangquery:is_jumping",undefined],
    ["mcwl:molangquery:is_laying_down",undefined],
    ["mcwl:molangquery:is_laying_egg",undefined],
    ["mcwl:molangquery:is_leashed",undefined],
    ["mcwl:molangquery:is_levitating",undefined],
    ["mcwl:molangquery:is_lingering",undefined],
    ["mcwl:molangquery:is_on_fire",undefined],
    ["mcwl:molangquery:is_on_ground",undefined],
    ["mcwl:molangquery:is_on_screen",undefined],
    ["mcwl:molangquery:is_orphaned",undefined],
    ["mcwl:molangquery:is_persona_or_premium_skin",undefined],
    ["mcwl:molangquery:is_playing_dead",undefined],
    ["mcwl:molangquery:is_powered",undefined],
    ["mcwl:molangquery:is_pregnant",undefined],
    ["mcwl:molangquery:is_ram_attacking",undefined],
    ["mcwl:molangquery:is_resting",undefined],
    ["mcwl:molangquery:is_riding",undefined],
    ["mcwl:molangquery:is_roaring",undefined],
    ["mcwl:molangquery:is_rolling",undefined],
    ["mcwl:molangquery:is_saddled",undefined],
    ["mcwl:molangquery:is_scared",undefined],
    ["mcwl:molangquery:is_selected_item",undefined],
    ["mcwl:molangquery:is_shaking",undefined],
    ["mcwl:molangquery:is_shaking_wetness",undefined],
    ["mcwl:molangquery:is_sheared",undefined],
    ["mcwl:molangquery:is_shield_powered",undefined],
    ["mcwl:molangquery:is_silent",undefined],
    ["mcwl:molangquery:is_sitting",undefined],
    ["mcwl:molangquery:is_sleeping",undefined],
    ["mcwl:molangquery:is_sneaking",undefined],
    ["mcwl:molangquery:is_sneezing",undefined],
    ["mcwl:molangquery:is_sprinting",undefined],
    ["mcwl:molangquery:is_stackable",undefined],
    ["mcwl:molangquery:is_stalking",undefined],
    ["mcwl:molangquery:is_standing",undefined],
    ["mcwl:molangquery:is_stunned",undefined],
    ["mcwl:molangquery:is_swimming",undefined],
    ["mcwl:molangquery:is_tamed",undefined],
    ["mcwl:molangquery:is_transforming",undefined],
    ["mcwl:molangquery:is_using_item",undefined],
    ["mcwl:molangquery:is_wall_climbing",undefined],
    ["mcwl:molangquery:out_of_control",undefined],
    ["mcwl:molangquery:show_bottom",undefined]   
])
export enum MolangNamespaces {
    blocking = "mcwl:molangquery:blocking",
    can_climb = "mcwl:molangquery:can_climb",
    can_damage_nearby_mobs = "mcwl:molangquery:can_damage_nearby_mobs",
    can_fly = "mcwl:molangquery:can_fly",
    can_power_jump = "mcwl:molangquery:can_power_jump",
    can_swim = "mcwl:molangquery:can_swim",
    can_walk = "mcwl:molangquery:can_walk",
    facing_target_to_range_attack = "mcwl:molangquery:facing_target_to_range_attack",
    has_cape = "mcwl:molangquery:has_cape",
    has_collision = "mcwl:molangquery:has_collision",
    has_gravity = "mcwl:molangquery:has_gravity",
    has_rider = "mcwl:molangquery:has_rider",
    has_target = "mcwl:molangquery:has_target",
    is_admiring = "mcwl:molangquery:is_admiring",
    is_alive = "mcwl:molangquery:is_alive",
    is_angry = "mcwl:molangquery:is_angry",
    is_attached_to_entity = "mcwl:molangquery:is_attached_to_entity",
    is_avoiding_block = "mcwl:molangquery:is_avoiding_block",
    is_avoiding_mobs = "mcwl:molangquery:is_avoiding_mobs",
    is_baby = "mcwl:molangquery:is_baby",
    is_breathing = "mcwl:molangquery:is_breathing",
    is_bribed = "mcwl:molangquery:is_bribed",
    is_carrying_block = "mcwl:molangquery:is_carrying_block",
    is_casting = "mcwl:molangquery:is_casting",
    is_celebrating = "mcwl:molangquery:is_celebrating",
    is_celebrating_special = "mcwl:molangquery:is_celebrating_special",
    is_charged = "mcwl:molangquery:is_charged",
    is_charging = "mcwl:molangquery:is_charging",
    is_chested = "mcwl:molangquery:is_chested",
    is_critical = "mcwl:molangquery:is_critical",
    is_croaking = "mcwl:molangquery:is_croaking",
    is_dancing = "mcwl:molangquery:is_dancing",
    is_delayed_attacking = "mcwl:molangquery:is_delayed_attacking",
    is_eating = "mcwl:molangquery:is_eating",
    is_eating_mob = "mcwl:molangquery:is_eating_mob",
    is_elder = "mcwl:molangquery:is_elder",
    is_emoting = "mcwl:molangquery:is_emoting",
    is_enchanted = "mcwl:molangquery:is_enchanted",
    is_fire_immune = "mcwl:molangquery:is_fire_immune",
    is_first_person = "mcwl:molangquery:is_first_person",
    is_ghost = "mcwl:molangquery:is_ghost",
    is_gliding = "mcwl:molangquery:is_gliding",
    is_grazing = "mcwl:molangquery:is_grazing",
    is_idling = "mcwl:molangquery:is_idling",
    is_ignited = "mcwl:molangquery:is_ignited",
    is_illager_captain = "mcwl:molangquery:is_illager_captain",
    is_in_contact_with_water = "mcwl:molangquery:is_in_contact_with_water",
    is_in_love = "mcwl:molangquery:is_in_love",
    is_in_ui = "mcwl:molangquery:is_in_ui",
    is_in_water = "mcwl:molangquery:is_in_water",
    is_in_water_or_rain = "mcwl:molangquery:is_in_water_or_rain",
    is_interested = "mcwl:molangquery:is_interested",
    is_invisible = "mcwl:molangquery:is_invisible",
    is_jumping = "mcwl:molangquery:is_jumping",
    is_laying_down = "mcwl:molangquery:is_laying_down",
    is_laying_egg = "mcwl:molangquery:is_laying_egg",
    is_leashed = "mcwl:molangquery:is_leashed",
    is_levitating = "mcwl:molangquery:is_levitating",
    is_lingering = "mcwl:molangquery:is_lingering",
    is_on_fire = "mcwl:molangquery:is_on_fire",
    is_on_ground = "mcwl:molangquery:is_on_ground",
    is_on_screen = "mcwl:molangquery:is_on_screen",
    is_orphaned = "mcwl:molangquery:is_orphaned",
    is_persona_or_premium_skin = "mcwl:molangquery:is_persona_or_premium_skin",
    is_playing_dead = "mcwl:molangquery:is_playing_dead",
    is_powered = "mcwl:molangquery:is_powered",
    is_pregnant = "mcwl:molangquery:is_pregnant",
    is_ram_attacking = "mcwl:molangquery:is_ram_attacking",
    is_resting = "mcwl:molangquery:is_resting",
    is_riding = "mcwl:molangquery:is_riding",
    is_roaring = "mcwl:molangquery:is_roaring",
    is_rolling = "mcwl:molangquery:is_rolling",
    is_saddled = "mcwl:molangquery:is_saddled",
    is_scared = "mcwl:molangquery:is_scared",
    is_selected_item = "mcwl:molangquery:is_selected_item",
    is_shaking = "mcwl:molangquery:is_shaking",
    is_shaking_wetness = "mcwl:molangquery:is_shaking_wetness",
    is_sheared = "mcwl:molangquery:is_sheared",
    is_shield_powered = "mcwl:molangquery:is_shield_powered",
    is_silent = "mcwl:molangquery:is_silent",
    is_sitting = "mcwl:molangquery:is_sitting",
    is_sleeping = "mcwl:molangquery:is_sleeping",
    is_sneaking = "mcwl:molangquery:is_sneaking",
    is_sneezing = "mcwl:molangquery:is_sneezing",
    is_sprinting = "mcwl:molangquery:is_sprinting",
    is_stackable = "mcwl:molangquery:is_stackable",
    is_stalking = "mcwl:molangquery:is_stalking",
    is_standing = "mcwl:molangquery:is_standing",
    is_stunned = "mcwl:molangquery:is_stunned",
    is_swimming = "mcwl:molangquery:is_swimming",
    is_tamed = "mcwl:molangquery:is_tamed",
    is_transforming = "mcwl:molangquery:is_transforming",
    is_using_item = "mcwl:molangquery:is_using_item",
    is_wall_climbing = "mcwl:molangquery:is_wall_climbing",
    out_of_control = "mcwl:molangquery:out_of_control",
    show_bottom = "mcwl:molangquery:show_bottom:true",
}