export enum MCWLNamespaces {
    sneakDuration = "mcwl:sneak_time",
    distanceTravelled = "mcwl:distance_travelled",
    sudo = "mcwl:sudo",
    blockInteractions = "mcwl:block_interactions",
    blocksModified = "mcwl:blocks_modified",
    playtime = "mcwl:playtime",
    playerJoined = "mcwl:player_joined",
    playerFirstJoined = "mcwl:player_first_joined",
    playerName = "mcwl:player_name",
    versionID = "mcwl:version_id",
    storageID = "mcwl:storage_id",
    deaths = "mcwl:deaths",
    timeSinceDeath = "mcwl:time_since_death",
    jump = "mcwl:jump",
    raidTrigger = "mcwl:raid_trigger",
    timeSinceRest = "mcwl:time_since_rest",
    sleepInBed = "mcwl:sleep_in_bed",
    health = "mcwl:health",
    animalsBred = "mcwl:animals_bred",
    fishCaught = "mcwl:fish_caught",
    enchantItem = "mcwl:enchant_item",
    drop = "mcwl:drop",
    mobKills = "mcwl:mob_kills",
    playerKills = "mcwl:player_kills",
    raidWin = "mcwl:raid_win",
    talkedToVillager = "mcwl:talked_to_villager",
    targetHit = "mcwl:target_hit",
    tradedWithVillager = "mcwl:traded_with_villager",

    menuWand_open = "mcwl.menu_wand.open"
}